# Configurations
title:            LC3Tutor
longtitle:        LC3Tutor
author:           thelc3tutor
github_username:  lc3tutor
email:            thelc3tutor@gmail.com

google_analytics: G-R10TKMEFBS

version:          1.0

url:              'https://lc3tutor.com'
#baseurl:          '/'
imageurl:         '/assets/lc3tutor/images/'
jsurl:            '/assets/lc3tutor/js/'
cssurl:           '/assets/lc3tutor/css/'
codeurl:          '/assets/lc3tutor/code/'

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
#permalink:                /:categories/:year-:month-:day-:title:output_ext
permalink: /:slug

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:slug

page_width: 900px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-sitemap
