# Configurations
title:            LC3Tutor
longtitle:        LC3Tutor
author:           thelc3tutor
github_username:  lc3tutor
email:            thelc3tutor@gmail.com
description: >
  A convinient place to put information about me.
  An online resume.

version:          1.0

url:              'https://lc3tutor.github.io'
#baseurl:          '/'
imageurl:         '/assets/lc3tutor/images/'

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
#permalink:                /:categories/:year-:month-:day-:title:output_ext
permalink: /:path/

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:path/

page_width: 900px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
